---
name: moarperf
cro: 1
id: moarperf
env:  []
links:  []
entrypoint: service.p6
endpoints:
  -
    port-env: MOARPERF_PORT
    name: HTTP
    protocol: http
    host-env: MOARPERF_HOST
    id: http
...
