language: node_js
node_js:
    - stable
install:
    - "cd frontend"
    - "npm ci"
test:
    - "true"
cache:
    directories:
        - "$HOME/.npm"

before-deploy:
    - "tar cjvf moarperf-(git rev-parse --short HEAD).tar.bz2 lib/*pm6 META6.json README.md service.p6 frontend/node_modules/bootstrap/dist/js/bootstrap.bundle.js{,.map} frontend/node_modules/bootstrap/dist/css/bootstrap{,-reboot,-grid}.css"

deploy:
  provider: releases
  file: moarperf-*.tar.bz2
  edge: true
